### PR TITLE
Removed `lib` from the repo

### PR DESCRIPTION
**Pull request by minlaxz**
- Removed `lib` from the repo which is no longer needed and now it's handled by GitHub actions.
- Updated Readme for better understanding.
- Cheers!

### CODE REVIEW

**Comment by luxysiv** [comment]
There are 3 problems in your pull request:
 * 1: If libs are removed, the script will no longer work on `Termux` because `Termux` cannot install the `aiohttp` library. `libs` will help scripts work faster because you don't have to install `aiohttp` 
 * 2: when someone forks the repository, the `dynamic_black_list` and `dynamic_white_list` will be taken from `main repository` , not `the fork person's repository`
 * 3 : `dotenv` will help scripts work in local easier. 
  
So sorry about my English.

**Comment by minlaxz** [comment]
> There are 3 problems in your pull request:
> 
> * 1: If `libs` are removed, the script will no longer work on `Termux` because `Termux` cannot install the `aiohttp` library. `libs` will help scripts work faster because you don't have to install `aiohttp`
> * 2: when someone forks the repository, the `dynamic_black_list` and `dynamic_white_list` will be taken from `main repository` , not `the fork person's repository`
> * 3 : `dotenv` will help scripts work in local easier.
> 
> So sorry about my English.

For problem No.1: I think we can install `aiohttp` on Termux, I have tested it.
My setup is using `python==3.11.6` and `aiohttp==3.8.6`.
_Note: Yeah I agreed with that this could be a bit longer only for the first setup._

For problem No.2: Let me figure it out.

For problem No.3: Using `dotenv` in the local machine like (Termux) is considered somewhat to be safe, so I think we can make another helper function to allow usage with `dotenv` only for using with Termux.

Please let me know what you think.

**Comment by luxysiv** [comment]
> > There are 3 problems in your pull request:
> > 
> > * 1: If `libs` are removed, the script will no longer work on `Termux` because `Termux` cannot install the `aiohttp` library. `libs` will help scripts work faster because you don't have to install `aiohttp`
> > * 2: when someone forks the repository, the `dynamic_black_list` and `dynamic_white_list` will be taken from `main repository` , not `the fork person's repository`
> > * 3 : `dotenv` will help scripts work in local easier.
> > 
> > So sorry about my English.
> 
> For problem No.1: I think we can install `aiohttp` on Termux, I have tested it. My setup is using `python==3.11.6` and `aiohttp==3.8.6`. _Note: Yeah I agreed with that this could be a bit longer only for the first setup._
> 
> For problem No.2: Let me figure it out.
> 
> For problem No.3: Using `dotenv` in the local machine like (Termux) is considered somewhat to be safe, so I think we can make another helper function to allow usage with `dotenv` only for using with Termux.
> 
> Please let me know what you think.

I wanna run `faster` so I put `libs` into script. And on `Termux`, only `clone` and `run`. I just only not delete libs. Every thing better you can PR

**Comment by luxysiv** [comment]
Have you thought about `dynamic_block_list` and `dynamic_white_list` yet?  Could you please redo the PR without asking to remove `lib`?  I have come up with a method to create `dynamic_block_list` and `dynamic_white_list`

**Comment by luxysiv** [comment]
Done `dynamic lists` . Thanks for your ideas. Can you re PR `Readme` ? Thanks again

**Comment by luxysiv** [comment]
>

**Comment by minlaxz** [comment]
Thank you, here's readme update #21, please let me know if anything I can help you with.

**Comment by luxysiv** [comment]
Can you make your native language introduce in docs/... look like vi.md?

**Pull request closed without merging**
